baseURL = '/'
languageCode = 'en-us'
title = 'Jorge Mota'
theme = "terminal"

[params]
title = "Jorge Mota"
# contentTypeName = "posts"
showMenuItems = 4
customCSS = ["css/main.css"]
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
autoCover = true
showLastUpdated = false
readingTime = false
Toc = false
favicon = "favicon.png"

[languages.en]
languageName = "English"
title = "Jorge Mota"
weight = 1

[languages.en.params.logo]
logoText = "Jorge Mota"
logoHomeLink = "/"
pageRef = '/projects'

###############################################################################
# About
###############################################################################

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

###############################################################################
# Projects
###############################################################################

[[languages.en.menu.main]]
identifier = "projects"
title = "Projects"
name = "Projects"
url = "/projects"
weight = 3

###############################################################################
# Posts
###############################################################################

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 2

[cascade.params]
readingTime = true
Toc = true
[cascade.target]
path = '{/posts,/posts/**}'


###############################################################################
# Resume
###############################################################################

[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "https://gh.killbyte.dev/cv/cv.pdf"
weight = 4
